require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")

ENV['NO_FLIPPER'] = '1' # Flipper 비활성화

require 'json'
podfile_properties = JSON.parse(File.read(File.join(__dir__, 'Podfile.properties.json'))) rescue {}

ENV['RCT_NEW_ARCH_ENABLED'] = podfile_properties['newArchEnabled'] == 'true' ? '1' : '0'
ENV['EX_DEV_CLIENT_NETWORK_INSPECTOR'] = podfile_properties['EX_DEV_CLIENT_NETWORK_INSPECTOR']


source 'https://github.com/expo/expo.git'
source 'https://cdn.cocoapods.org/'


platform :ios, '15.1'
install! 'cocoapods',
  :deterministic_uuids => false

pod 'GoogleUtilities', :modular_headers => true
pod 'FirebaseCoreInternal', :modular_headers => true
pod 'FirebaseCore', :modular_headers => true
pod 'FirebaseInstallations', :modular_headers => true
pod 'RNFBApp', :path => '../node_modules/@react-native-firebase/app', :modular_headers => false

  

prepare_react_native_project!

target 'app' do
  use_expo_modules!

  # use_frameworks! :linkage => :static

  if ENV['EXPO_USE_COMMUNITY_AUTOLINKING'] == '1'
    config_command = ['node', '-e', "process.argv=['', '', 'config'];require('@react-native-community/cli').run()"];
  else
    config_command = [
      'node',
      '--no-warnings',
      '--eval',
      'require(require.resolve(\'expo-modules-autolinking\', { paths: [require.resolve(\'expo/package.json\')] }))(process.argv.slice(1))',
      'react-native-config',
      '--json',
      '--platform',
      'ios'
    ]
  end

  config = use_native_modules!(config_command)

  # 프레임워크 사용 옵션 수정
  if podfile_properties['ios.useFrameworks']
    use_frameworks! :linkage => podfile_properties['ios.useFrameworks'].to_sym
  elsif ENV['USE_FRAMEWORKS']
    use_frameworks! :linkage => ENV['USE_FRAMEWORKS'].to_sym
  else
    # Expo와 React Native의 호환성을 위해 정적 링크 사용
    use_frameworks! :linkage => :static
  end
  
  # React Native와 Swift 호환성을 위한 설정
  ENV['RCT_USE_WAITTING_MODE_FOR_SWIFT'] = '1'

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => podfile_properties['expo.jsEngine'] == nil || podfile_properties['expo.jsEngine'] == 'hermes',
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :privacy_file_aggregation_enabled => podfile_properties['apple.privacyManifestAggregationEnabled'] != 'false'
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      :ccache_enabled => podfile_properties['apple.ccacheEnabled'] == 'true',
    )

    # React Native 관련 설정 개선
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        # 모든 타겟에 기본 헤더 경로 설정
        config.build_settings['HEADER_SEARCH_PATHS'] ||= '$(inherited)'
        
        # C++ 표준 버전 업데이트 - C++20으로 변경
        config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++20'
        
        # 추가 C++ 오류 해결을 위한 컴파일러 플래그
        config.build_settings['OTHER_CPLUSPLUSFLAGS'] ||= '$(inherited)'
        config.build_settings['OTHER_CPLUSPLUSFLAGS'] << ' -std=c++20'
        
        # 추가 헤더 경로 설정
        additional_paths = [
          "${PODS_ROOT}/Headers/Public/React-Core", 
          "${PODS_ROOT}/Headers/Public/React",
          "${PODS_ROOT}/Headers/Public/React-debug",
          "${PODS_ROOT}/Headers/Public/ReactCommon",
          "${PODS_ROOT}/Headers/Public/React-utils",
          "${PODS_CONFIGURATION_BUILD_DIR}/React-Core/React_Core.framework/Headers",
          "${PODS_CONFIGURATION_BUILD_DIR}/React-debug/React_debug.framework/Headers",
          "${PODS_TARGET_SRCROOT}/../..",
          "${PODS_ROOT}/Headers/Public/React-debug/react/debug",
          "${PODS_ROOT}/Headers/Public/React-utils/react/utils",
          "${PODS_ROOT}/Headers/Public/React-rendererdebug/react/renderer/debug",
          "${PODS_ROOT}/Headers/Public/React-rendererdebug/react/renderer/debug/react/renderer/debug",
          "${PODS_ROOT}/Headers/Private/React-rendererdebug/react/renderer/debug/react/renderer/debug",
          "${PODS_ROOT}/Headers/Private/React-featureflags/react/featureflags/react/featureflags",
          "${PODS_ROOT}/Headers/Public/React-featureflags/react/featureflags/react/featureflags"
        ]
        
        # 헤더 경로 추가
        additional_paths.each do |path|
          config.build_settings['HEADER_SEARCH_PATHS'] << " #{path}"
        end
        
        # React-Core 모듈 관련 설정
        if ['React-Core', 'React-RCTActionSheet', 'React-RCTAnimation', 'React-RCTBlob', 'React-RCTImage', 'React-RCTLinking', 'React-RCTNetwork', 'React-RCTSettings', 'React-RCTText', 'React-RCTVibration'].include? target.name
          config.build_settings['CLANG_ENABLE_MODULES'] = 'YES'
          config.build_settings['DEFINES_MODULE'] = 'YES'
          config.build_settings['SWIFT_OBJC_BRIDGING_HEADER'] = '"${PODS_ROOT}/Headers/Public/React-Core/React/RCTBridgeModule.h"'
        end

        # 필요에 따라 특정 타겟에 추가 설정
        if ['React-utils', 'ReactCommon', 'React-debug'].include? target.name
          # C++ 요구사항 및 헤더 가시성
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'RCT_METRO_PORT=${RCT_METRO_PORT}'
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'FOLLY_NO_CONFIG=1 FOLLY_MOBILE=1 FOLLY_USE_LIBCPP=1'
          config.build_settings['OTHER_CPLUSPLUSFLAGS'] = '$(inherited) -DFOLLY_NO_CONFIG -DFOLLY_MOBILE=1 -DFOLLY_USE_LIBCPP=1'
        end
        
        # React-utils에서 react_native_assert.h 파일을 찾지 못하는 문제 해결
        if target.name == 'React-utils'
          # 해당 헤더가 필요하지 않도록 설정
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'REACT_NATIVE_DEBUG=0'
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'RCT_FOLLY_REACTNATIVE_ASSERT=0'
          
          # 추가 컴파일러 플래그 - 헤더 관련 오류 무시
          config.build_settings['OTHER_CFLAGS'] ||= '$(inherited)'
          config.build_settings['OTHER_CFLAGS'] << ' -Wno-error=implicit-function-declaration -Wno-error=quoted-include-in-framework-header -Wno-everything -Wno-error'
          
          # 소스 파일에서 RunLoopObserver.cpp 제외
          config.build_settings['EXCLUDED_SOURCE_FILE_NAMES'] ||= []
          config.build_settings['EXCLUDED_SOURCE_FILE_NAMES'] << '**/RunLoopObserver.cpp'
        end
      end
    end

    # This is necessary for Xcode 14, because it signs resource bundles by default
    # when building for devices.
    installer.target_installation_results.pod_target_installation_results
      .each do |pod_name, target_installation_result|
      target_installation_result.resource_bundle_targets.each do |resource_bundle_target|
        resource_bundle_target.build_configurations.each do |config|
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
      end
    end
  end
end
